# version: "3.8"

services:
  banking-backend:
    container_name: banking-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${SERVER_PORT:-8080}:8080"
    networks:
      - banking-network
    env_file:
      - .env
    volumes:
      - .:/app 
      - maven-repo:/root/.m2 
    restart: unless-stopped

networks:
  banking-network:
    driver: bridge

volumes:
  maven-repo:
