spring.application.name: backend

server.port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://ep-red-sky-a1clgzvm-pooler.ap-southeast-1.aws.neon.tech:5432/bankdb?sslmode=require
    username: neondb_owner
    password: npg_FZ2GHlUcWk9y
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 900000
      pool-name: HikariPool-FoodService
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
  data.redis:
    database: 0
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: 60000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  jwt:
    secret: ${JWT_SECRET_KEY}
  refresh:
    expiration: 2592000

google:
  recaptcha:
    key:
      secret: ${GG_SECRET_KEY}

app:
  mail:
    from: ${MAIL_USERNAME}
    from-name: "FINTECH HCMUS"